### ISSUE TITLE
iwads allow duplicate entries

### ISSUE THREAD

**Issue by nstlaurent** [nstlaurent/DoomLauncher#155]
The actual game file is not duplicated, the iwad gets linked to same game file.

**Comment by nstlaurent** [comment]
fixed on development

**Comment by Chonkblonk** [comment]
I still get this with the latest update. There's no option for removing iwads from Doom Launcher, just to add.
![bild](https://github.com/nstlaurent/DoomLauncher/assets/114463804/b572fa33-73f0-4b95-9523-1b3ce0bede8d)

To expand on this a bit, rather than linking Doom Launcher to whichever folder of whatever version of what sourceport I am using, I made a special folder for just having the iwads in, and now it makes a lot of the duplicate entries not work.

**Comment by Chonkblonk** [comment]
Oh wait, I can enable an iwad view, not sure I could do that in an older version.
